# Generated by Django 4.0.1 on 2022-01-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='text',
            new_name='content',
        ),
    ]
