# Generated by Django 4.0.1 on 2022-02-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_alter_memo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
