# Generated by Django 4.0.1 on 2022-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_alter_memo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='create_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
