# Generated by Django 4.0.1 on 2022-02-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_id_alter_profile_nickname'),
        ('memo', '0005_alter_memo_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
